// Code generated by mockery v2.16.0. DO NOT EDIT.

package crawler

import mock "github.com/stretchr/testify/mock"

// mockStorer is an autogenerated mock type for the storer type
type mockStorer struct {
	mock.Mock
}

// StoreResponse provides a mock function with given fields: res
func (_m *mockStorer) StoreResponse(res Response) error {
	ret := _m.Called(res)

	var r0 error
	if rf, ok := ret.Get(0).(func(Response) error); ok {
		r0 = rf(res)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTnewMockStorer interface {
	mock.TestingT
	Cleanup(func())
}

// newMockStorer creates a new instance of mockStorer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockStorer(t mockConstructorTestingTnewMockStorer) *mockStorer {
	mock := &mockStorer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
